name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: flake8
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker compose run --rm app sh -c "python -m flake8"
  test:
    needs: lint
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python3 manage.py test"

  push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: push image to dockerhub
        run: |
          echo "Pushing docker image to DockerHub"
          docker build -t dolar-price-prediction .
          docker tag dolar-price-prediction:latest timosch99/dolar-price-prediction:latest
          docker push timosch99/dolar-price-prediction:latest